const loginCopy = {
  'zh-TW': {
    brand: 'Sink',
    adminAccess: '管理員登入',
    workspaceTitle: '清楚掌握每一條連結。',
    workspaceDescription: '建立與整理短網址，並查看連結成效。',
    samplePath: '連結跳轉示意',
    originalUrl: '原始連結',
    shortUrl: '短網址',
    footer: '使用裝置驗證後即可繼續。',
    title: '使用 Passkey 登入',
    description: '使用 Touch ID、Face ID、Windows Hello 或已儲存的 Passkey 登入。',
    passkeyAction: '使用 Passkey 登入',
    passkeyWaiting: '請在裝置上完成驗證…',
    passkeyUnsupported: 'Passkey 需要支援的瀏覽器與安全的 HTTPS 連線。',
    passkeyFailed: 'Passkey 登入未完成，請重試或改用 Site Token。',
    passkeyUnregistered: '尚未註冊 Passkey。請先用 Site Token 登入，再到「設定 → Security」新增。',
    tokenHeading: '改用 Site Token',
    tokenDescription: 'Site Token 仍可供 API 整合使用。',
    tokenPlaceholder: '輸入 Site Token',
    tips: '提示',
    previewToken: '預覽模式的 Site Token 是',
    tokenSubmit: '使用 Token 登入',
    tokenFailed: 'Site Token 無效，請確認後再試一次。',
  },
  'zh-CN': {
    brand: 'Sink',
    adminAccess: '管理员登录',
    workspaceTitle: '清晰管理每一条链接。',
    workspaceDescription: '创建和整理短链接，并查看链接表现。',
    samplePath: '链接跳转示意',
    originalUrl: '原始链接',
    shortUrl: '短链接',
    footer: '通过设备验证后即可继续。',
    title: '使用 Passkey 登录',
    description: '使用 Touch ID、Face ID、Windows Hello 或已保存的 Passkey 登录。',
    passkeyAction: '使用 Passkey 登录',
    passkeyWaiting: '请在设备上完成验证…',
    passkeyUnsupported: 'Passkey 需要受支持的浏览器和安全的 HTTPS 连接。',
    passkeyFailed: 'Passkey 登录未完成，请重试或改用 Site Token。',
    passkeyUnregistered: '尚未注册 Passkey。请先用 Site Token 登录，再到“设置 → Security”添加。',
    tokenHeading: '改用 Site Token',
    tokenDescription: 'Site Token 仍可用于 API 集成。',
    tokenPlaceholder: '输入 Site Token',
    tips: '提示',
    previewToken: '预览模式的 Site Token 是',
    tokenSubmit: '使用 Token 登录',
    tokenFailed: 'Site Token 无效，请检查后重试。',
  },
  'en-US': {
    brand: 'Sink',
    adminAccess: 'Administrator access',
    workspaceTitle: 'Your links, clearly managed.',
    workspaceDescription: 'Create and organize short links, then review how they perform.',
    samplePath: 'Example redirect',
    originalUrl: 'Original link',
    shortUrl: 'Short link',
    footer: 'Confirm with your device to continue.',
    title: 'Sign in with a passkey',
    description: 'Use Touch ID, Face ID, Windows Hello, or another saved passkey.',
    passkeyAction: 'Continue with a passkey',
    passkeyWaiting: 'Waiting for your device…',
    passkeyUnsupported: 'Passkeys need a supported browser and a secure HTTPS connection.',
    passkeyFailed: 'Passkey sign-in did not complete. Try again or use your Site Token.',
    passkeyUnregistered: 'No passkey is registered yet. Sign in with your Site Token, then add one in Settings → Security.',
    tokenHeading: 'Use your Site Token',
    tokenDescription: 'Your Site Token remains available for API integrations.',
    tokenPlaceholder: 'Enter your Site Token',
    tips: 'Tip',
    previewToken: 'The preview Site Token is',
    tokenSubmit: 'Sign in with token',
    tokenFailed: 'The Site Token was rejected. Check it and try again.',
  },
  'fr-FR': {
    brand: 'Sink',
    adminAccess: 'Accès administrateur',
    workspaceTitle: 'Gérez vos liens en toute clarté.',
    workspaceDescription: 'Créez et organisez vos liens courts, puis consultez leurs performances.',
    samplePath: 'Exemple de redirection',
    originalUrl: 'Lien d’origine',
    shortUrl: 'Lien court',
    footer: 'Confirmez avec votre appareil pour continuer.',
    title: 'Se connecter avec une passkey',
    description: 'Utilisez Touch ID, Face ID, Windows Hello ou une passkey enregistrée.',
    passkeyAction: 'Continuer avec une passkey',
    passkeyWaiting: 'Confirmez sur votre appareil…',
    passkeyUnsupported: 'Les passkeys nécessitent un navigateur compatible et une connexion HTTPS sécurisée.',
    passkeyFailed: 'La connexion par passkey n’a pas abouti. Réessayez ou utilisez le Site Token.',
    passkeyUnregistered: 'Aucune passkey n’est enregistrée. Connectez-vous avec le Site Token, puis ajoutez-en une dans Paramètres → Security.',
    tokenHeading: 'Utiliser le Site Token',
    tokenDescription: 'Le Site Token reste disponible pour les intégrations API.',
    tokenPlaceholder: 'Saisissez votre Site Token',
    tips: 'Astuce',
    previewToken: 'Le Site Token de démonstration est',
    tokenSubmit: 'Connexion avec le token',
    tokenFailed: 'Le Site Token est invalide. Vérifiez-le et réessayez.',
  },
  'de-DE': {
    brand: 'Sink',
    adminAccess: 'Administratorzugang',
    workspaceTitle: 'Behalte deine Links im Blick.',
    workspaceDescription: 'Erstelle und organisiere Kurzlinks und prüfe ihre Leistung.',
    samplePath: 'Beispiel für eine Weiterleitung',
    originalUrl: 'Ursprünglicher Link',
    shortUrl: 'Kurzlink',
    footer: 'Bestätige mit deinem Gerät, um fortzufahren.',
    title: 'Mit Passkey anmelden',
    description: 'Nutze Touch ID, Face ID, Windows Hello oder einen gespeicherten Passkey.',
    passkeyAction: 'Mit Passkey fortfahren',
    passkeyWaiting: 'Bestätige auf deinem Gerät…',
    passkeyUnsupported: 'Passkeys benötigen einen kompatiblen Browser und eine sichere HTTPS-Verbindung.',
    passkeyFailed: 'Die Passkey-Anmeldung wurde nicht abgeschlossen. Versuche es erneut oder nutze deinen Site Token.',
    passkeyUnregistered: 'Es ist noch kein Passkey registriert. Melde dich mit dem Site Token an und füge unter Einstellungen → Security einen hinzu.',
    tokenHeading: 'Site Token verwenden',
    tokenDescription: 'Der Site Token bleibt für API-Integrationen verfügbar.',
    tokenPlaceholder: 'Site Token eingeben',
    tips: 'Hinweis',
    previewToken: 'Der Site Token für die Vorschau lautet',
    tokenSubmit: 'Mit Token anmelden',
    tokenFailed: 'Der Site Token wurde abgelehnt. Prüfe ihn und versuche es erneut.',
  },
  'vi-VN': {
    brand: 'Sink',
    adminAccess: 'Quyền quản trị',
    workspaceTitle: 'Quản lý liên kết rõ ràng hơn.',
    workspaceDescription: 'Tạo và sắp xếp liên kết ngắn, sau đó xem hiệu quả của chúng.',
    samplePath: 'Ví dụ chuyển hướng',
    originalUrl: 'Liên kết gốc',
    shortUrl: 'Liên kết ngắn',
    footer: 'Xác nhận bằng thiết bị để tiếp tục.',
    title: 'Đăng nhập bằng Passkey',
    description: 'Dùng Touch ID, Face ID, Windows Hello hoặc Passkey đã lưu.',
    passkeyAction: 'Tiếp tục bằng Passkey',
    passkeyWaiting: 'Hãy xác nhận trên thiết bị…',
    passkeyUnsupported: 'Passkey cần trình duyệt tương thích và kết nối HTTPS an toàn.',
    passkeyFailed: 'Đăng nhập bằng Passkey chưa hoàn tất. Hãy thử lại hoặc dùng Site Token.',
    passkeyUnregistered: 'Chưa có Passkey. Hãy đăng nhập bằng Site Token rồi thêm Passkey trong Settings → Security.',
    tokenHeading: 'Dùng Site Token',
    tokenDescription: 'Site Token vẫn dùng được cho các tích hợp API.',
    tokenPlaceholder: 'Nhập Site Token',
    tips: 'Gợi ý',
    previewToken: 'Site Token ở chế độ xem trước là',
    tokenSubmit: 'Đăng nhập bằng token',
    tokenFailed: 'Site Token không hợp lệ. Hãy kiểm tra và thử lại.',
  },
} as const

export function useLoginCopy() {
  const { locale } = useI18n()
  const siteBrand = useSiteBrand()
  return computed(() => {
    const base = loginCopy[locale.value as keyof typeof loginCopy] || loginCopy['zh-TW']
    return {
      ...base,
      brand: siteBrand.value || base.brand,
    }
  })
}
